import FoC.Computability.Compiler.Core.FiniteScaffolds.ControllerOutputLevelSimulator
import FoC.Computability.Compiler.Core.StructuredConstructionTargets

set_option doc.verso true

/-!
# Controller fuel-pair search bridge

This module isolates the bounded {lit}`(limit, fuel)` pair enumerator and the
classifier handoff used by the controller search driver.
-/

namespace FoC
namespace Computability

open Languages
open MachineDescription
open StructuredConstructionTargets

private theorem pairedRecognizerDovetailControllerStageAttemptBoundedFuelPairEnumeratorStructuredRightShiftedSpecConstruction_finite_leaf :
    PairedRecognizerDovetailControllerStageAttemptBoundedFuelPairEnumeratorStructuredRightShiftedSpecConstruction :=
  pairedRecognizerDovetailControllerStageAttemptBoundedFuelPairEnumeratorStructuredRightShiftedSpecConstruction_structuredLeaf

private theorem pairedRecognizerDovetailControllerStageAttemptBoundedFuelPairEnumeratorRightShiftedSpecConstruction_finite_leaf :
    PairedRecognizerDovetailControllerStageAttemptBoundedFuelPairEnumeratorRightShiftedSpecConstruction :=
  pairedRecognizerDovetailControllerStageAttemptBoundedFuelPairEnumeratorRightShiftedSpecConstruction_of_structured
    pairedRecognizerDovetailControllerStageAttemptBoundedFuelPairEnumeratorStructuredRightShiftedSpecConstruction_finite_leaf

theorem pairedRecognizerDovetailControllerStageAttemptFuelPairSearchConstruction_finite_leaf :
    PairedRecognizerDovetailControllerStageAttemptFuelPairSearchConstruction :=
  pairedRecognizerDovetailControllerStageAttemptFuelPairSearchConstruction_of_boundedRightShiftedEnumerator_emitter
    pairedRecognizerDovetailControllerStageAttemptBoundedFuelPairEnumeratorRightShiftedSpecConstruction_finite_leaf
    pairedRecognizerDovetailControllerBoolWordRawOutputEmitterConstruction_scaffold

end Computability
end FoC
