import FoC.Computability.Compiler.ClosedCfg.ProjTail.ScratchBridge.InputMat.IndexedMaterializer.RejectCompose

set_option doc.verso true

/-!
# Count-window input materializer constructions

Public wrappers for the completed indexed count-window materializer.
-/

namespace FoC
namespace Computability

open Languages
open MachineDescription
open CommonGround.FiniteTransducers
open CommonGround.FiniteTransducers.Structured.MultiTapeLowering

namespace EncRewriters
namespace BoundedLayoutRunner
namespace SelectedProjectionPaddedTailCleanup

open CanonicalLayouts.DovetailLayoutScanner

theorem countWindowPostFieldDecodedPrefixStructuredBoolWordMaterializerConstruction_core :
    CountWindowPostFieldDecodedPrefixStructuredBoolWordMaterializerConstruction := by
  exact
    countWindowPostFieldDecodedPrefixStructuredBoolWordMaterializerConstruction_of_indexed
      InputMat.Route.IndexedConstruction.indexedBoolWordMaterializerConstruction

theorem countWindowPostFieldDecodedPrefixStructuredInputMaterializerConstruction_core :
    CountWindowPostFieldDecodedPrefixStructuredInputMaterializerConstruction := by
  exact
    countWindowPostFieldDecodedPrefixStructuredInputMaterializerConstruction_of_boolWord
      countWindowPostFieldDecodedPrefixStructuredBoolWordMaterializerConstruction_core

theorem countWindowPostFieldDecodedPrefixStructuredInputInitializerConstruction_core :
    CountWindowPostFieldDecodedPrefixStructuredInputInitializerConstruction := by
  exact
    countWindowPostFieldDecodedPrefixStructuredInputInitializerConstruction_of_structured3InputMaterializer
      countWindowPostFieldDecodedPrefixStructuredInputMaterializerConstruction_core

end SelectedProjectionPaddedTailCleanup
end BoundedLayoutRunner
end EncRewriters

end Computability
end FoC
