import FoC.Book.Chapter04.Section06.Basics
import FoC.Book.Chapter04.Section06.EqualCounts
import FoC.Book.Chapter04.Section06.FourCounts
import FoC.Book.Chapter04.Section06.OrderedABC
import FoC.Book.Chapter04.Section06.OrderedABCD
import FoC.Book.Chapter04.Section06.StrictInequalities
import FoC.Book.Chapter04.Section06.UnarySquares
import FoC.Book.Chapter04.Section06.PowersOfTwo

set_option doc.verso true

/-!
# Chapter 4, Section 4.6: General Grammars

Book: Section 4.6 (General Grammars), covering the three sample grammars of
the section body and Exercises 3 and 4.

This wrapper exposes the unrestricted-grammar examples and bridge material for
Chapter 5. The basic files introduce general grammar vocabulary and finite
presentations; the example modules cover equal-count and ordered-block
languages, strict inequalities, unary squares, and the power-of-two unary
family.

One modeling caveat: the book's definition of a grammar requires both the
nonterminal set and the terminal alphabet to be finite, while the reusable
{module}`FoC.Grammars.GeneralGrammar` structure carries finiteness evidence
only for the nonterminal type and places no finiteness requirement on the
terminal type. The examples in this section all use small inductive terminal
types, which are finite, but the model itself does not enforce terminal
finiteness.

Formalization status: the equal-count grammars in
{module}`FoC.Book.Chapter04.Section06.EqualCounts` and
{module}`FoC.Book.Chapter04.Section06.FourCounts`, the ordered three-block
grammar in {module}`FoC.Book.Chapter04.Section06.OrderedABC`, the unary-square
grammar in {module}`FoC.Book.Chapter04.Section06.UnarySquares`, and the
warm-up strict-more-b grammar prove exact generated-language equalities. Three
exercise grammars are only partially verified.
{module}`FoC.Book.Chapter04.Section06.OrderedABCD` (Exercise 4a) proves count
preservation and witness derivations only; neither inclusion of the language
equality with the ordered four-block language is proved.
{module}`FoC.Book.Chapter04.Section06.PowersOfTwo` (Exercise 4e) proves the
generation direction for the whole power-of-two family unconditionally, but
its exactness theorem is conditional on an unproved soundness assumption.
{module}`FoC.Book.Chapter04.Section06.StrictInequalities` (Exercise 4f) proves
the soundness direction and witness derivations only; generation of every word
with strictly decreasing counts is not proved.

The book's countability conclusion, that only countably many languages arise
from finite presentations and hence some language over a fixed alphabet is
generated by no grammar, is represented only by the countability of
presentation codes in {module}`FoC.Book.Chapter04.Section06.Basics`. The
uncountability of languages and the resulting existence statement are not
formalized.
-/
