import FoC.Grammars.CFL
import FoC.Languages.Regular
import FoC.Languages.NFAPath

set_option doc.verso true

/-!
# Right-regular grammars

## Right-linear productions

Right-regular grammars sit at the boundary between Chapter 3 and Chapter 4.
This module builds the finite-automaton interpretation of right-regular
productions and records the equivalence with regular languages.

## Book coordinates

Used by:
- Chapter 4, Section 4.1: Theorem 4.4, equivalence between regular languages
  and languages generated by right-regular grammars.
-/

namespace FoC
namespace Grammars

open Foundation
open Languages

namespace CFG

/-!
# NFA interpretation

A right-regular grammar can be read as an NFA whose states are nonterminals:
terminal-plus-nonterminal productions become symbol transitions, epsilon
productions become accepting states, and nonterminal-only productions become
epsilon transitions.
-/

def AcceptedFrom (M : NFA terminal state) (q : state) : Language terminal :=
  fun w => exists r, NFA.Path M q w r ∧ M.accept r

def RightRegularNFA (G : CFG terminal nt) : NFA terminal nt where
  start := G.start
  step := fun A input B =>
    match input with
    | none => G.produces A [Symbol.nonterminal B]
    | some a => G.produces A [Symbol.terminal a, Symbol.nonterminal B]
  accept := fun A => G.produces A []
  statesFinite := G.nonterminalsFinite

def RightRegularSymbolLanguage (G : CFG terminal nt) :
    Symbol terminal nt -> Language terminal
  | Symbol.terminal a => Language.Singleton (Word.Symbol a)
  | Symbol.nonterminal A => AcceptedFrom (RightRegularNFA G) A

/-!
# Soundness toward automata

These lemmas show that generated words of a right-regular grammar are accepted
by its associated NFA.
-/

theorem rightRegularNFA_path_derives (G : CFG terminal nt)
    {A B : nt} {w : Word terminal}
    (hpath : NFA.Path (RightRegularNFA G) A w B) :
    Derives G [Symbol.nonterminal A]
      (SententialForm.terminalWord w ++ [Symbol.nonterminal B]) := by
  induction hpath with
  | nil q =>
      exact Derives.refl _
  | eps hstep _htail ih =>
      rename_i q r _s _tail
      have hYield : Yields G [Symbol.nonterminal q] [Symbol.nonterminal r] := by
        exists []
        exists []
        exists q
        exists [Symbol.nonterminal r]
      exact derives_trans (yields_derives hYield) ih
  | sym hstep _htail ih =>
      rename_i q r s a tail
      have hYield : Yields G [Symbol.nonterminal q]
          [Symbol.terminal a, Symbol.nonterminal r] := by
        exists []
        exists []
        exists q
        exists [Symbol.terminal a, Symbol.nonterminal r]
      have hPrefix : Derives G [Symbol.nonterminal q]
          [Symbol.terminal a, Symbol.nonterminal r] :=
        yields_derives hYield
      have hTail : Derives G [Symbol.terminal a, Symbol.nonterminal r]
          (Symbol.terminal a ::
            (SententialForm.terminalWord tail ++ [Symbol.nonterminal s])) := by
        simpa using derives_context ih [Symbol.terminal a] []
      have hAll := derives_trans hPrefix hTail
      simpa [SententialForm.terminalWord] using hAll

theorem rightRegularNFA_accepts_to_generates (G : CFG terminal nt)
    {w : Word terminal}
    (h : w ∈ NFA.AcceptedLanguage (RightRegularNFA G)) :
    w ∈ GeneratedLanguage G := by
  cases (NFA.pathAccepts_iff_accepts (RightRegularNFA G) w).mpr h with
  | intro q hq =>
      have hPrefix := rightRegularNFA_path_derives G hq.left
      have hFinalYield : Yields G
          (SententialForm.terminalWord w ++ [Symbol.nonterminal q])
          (SententialForm.terminalWord w) := by
        have hLocal : Yields G [Symbol.nonterminal q] [] := by
          exists []
          exists []
          exists q
          exists ([] : SententialForm terminal nt)
          constructor
          · exact hq.right
          constructor <;> rfl
        simpa using yields_context hLocal (SententialForm.terminalWord w) []
      exact derives_trans hPrefix (yields_derives hFinalYield)

theorem rightRegular_production_sound (G : CFG terminal nt)
    (hrr : RightRegular G)
    {A : nt} {rhs : SententialForm terminal nt}
    (hprod : G.produces A rhs) :
    forall w, w ∈ FormLanguage (RightRegularSymbolLanguage G) rhs ->
      w ∈ AcceptedFrom (RightRegularNFA G) A := by
  intro w hw
  cases hrr A rhs hprod with
  | epsilon =>
      cases hw
      exists A
      constructor
      · exact NFA.Path.nil A
      · exact hprod
  | nonterminal B =>
      cases hw with
      | intro first hfirst =>
          cases hfirst with
          | intro tail htail =>
              cases htail.right.left
              rw [htail.right.right, Word.concat_empty_right]
              cases htail.left with
              | intro q hq =>
                  exists q
                  constructor
                  · exact NFA.Path.eps hprod hq.left
                  · exact hq.right
  | terminalThenNonterminal a B =>
      cases hw with
      | intro first hfirst =>
          cases hfirst with
          | intro tail htail =>
              have hfirst : first = Word.Symbol a := htail.left
              rw [htail.right.right, hfirst]
              cases htail.right.left with
              | intro middle hmiddle =>
                  cases hmiddle with
                  | intro rest hrest =>
                    cases hrest.right.left
                    rw [hrest.right.right, Word.concat_empty_right]
                    cases hrest.left with
                    | intro q hq =>
                      exists q
                      constructor
                      · exact NFA.Path.sym hprod hq.left
                      · exact hq.right

theorem rightRegular_yields_sound (G : CFG terminal nt)
    (hrr : RightRegular G)
    {x y : SententialForm terminal nt} {w : Word terminal}
    (h : Yields G x y)
    (hw : w ∈ FormLanguage (RightRegularSymbolLanguage G) y) :
    w ∈ FormLanguage (RightRegularSymbolLanguage G) x := by
  cases h with
  | intro u hu =>
      cases hu with
      | intro v hv =>
          cases hv with
          | intro A hA =>
              cases hA with
              | intro rhs hrhs =>
                  cases hrhs with
                  | intro hprod hrest =>
                      cases hrest with
                      | intro hx hy =>
                          rw [hy] at hw
                          rw [hx]
                          exact formLanguage_replace_sound
                            (RightRegularSymbolLanguage G)
                            (rightRegular_production_sound G hrr hprod)
                            hw

theorem rightRegular_derives_sound (G : CFG terminal nt)
    (hrr : RightRegular G)
    {x y : SententialForm terminal nt} {w : Word terminal}
    (h : Derives G x y)
    (hw : w ∈ FormLanguage (RightRegularSymbolLanguage G) y) :
    w ∈ FormLanguage (RightRegularSymbolLanguage G) x := by
  induction h with
  | refl _ =>
      exact hw
  | step hstep _ ih =>
      exact rightRegular_yields_sound G hrr hstep (ih hw)

theorem rightRegular_generates_to_nfa_accepts (G : CFG terminal nt)
    (hrr : RightRegular G) {w : Word terminal}
    (h : w ∈ GeneratedLanguage G) :
    w ∈ NFA.AcceptedLanguage (RightRegularNFA G) := by
  have hterminal : w ∈ FormLanguage (RightRegularSymbolLanguage G)
      (SententialForm.terminalWord (nt := nt) w) :=
    terminalWord_mem_formLanguage (RightRegularSymbolLanguage G) (by intro a; rfl) w
  have hsound := rightRegular_derives_sound G hrr h hterminal
  cases hsound with
  | intro first hfirst =>
      cases hfirst with
      | intro tail htail =>
          cases htail.right.left
          exact (NFA.pathAccepts_iff_accepts (RightRegularNFA G) w).mp (by
            rw [htail.right.right, Word.concat_empty_right]
            exact htail.left)

theorem rightRegularNFA_language_exact (G : CFG terminal nt)
    (hrr : RightRegular G) :
    Language.Equal (GeneratedLanguage G) (NFA.AcceptedLanguage (RightRegularNFA G)) := by
  intro w
  constructor
  · exact rightRegular_generates_to_nfa_accepts G hrr
  · exact rightRegularNFA_accepts_to_generates G

/-!
# Regular grammar language classes

The language-level predicates abstract away the concrete nonterminal type while
retaining the right-regular or left-regular production shape.
-/

def RightRegularLanguage (L : Language terminal) : Prop :=
  exists nt : Type, exists G : CFG terminal nt,
    RightRegular G ∧ Language.Equal (GeneratedLanguage G) L

def LeftRegularLanguage (L : Language terminal) : Prop :=
  exists nt : Type, exists G : CFG terminal nt,
    LeftRegular G ∧ Language.Equal (GeneratedLanguage G) L

/-!
# Left and right regularity

Left-regular languages are related to right-regular languages by reversal,
matching the textbook equivalence proof.
-/

theorem leftRegularLanguage_reverse_rightRegular {L : Language terminal}
    (hL : LeftRegularLanguage L) :
    RightRegularLanguage (Language.Reverse L) := by
  cases hL with
  | intro nt hnt =>
      cases hnt with
      | intro G hG =>
          exists nt
          exists ReverseGrammar G
          constructor
          · exact leftRegular_reverseGrammar_rightRegular hG.left
          · intro w
            constructor
            · intro hw
              have hrev :=
                (reverseGrammar_language_exact G w).mp hw
              exact (hG.right (Word.Reverse w)).mp hrev
            · intro hw
              exact (reverseGrammar_language_exact G w).mpr
                ((hG.right (Word.Reverse w)).mpr hw)

theorem rightRegularLanguage_reverse_leftRegular {L : Language terminal}
    (hL : RightRegularLanguage L) :
    LeftRegularLanguage (Language.Reverse L) := by
  cases hL with
  | intro nt hnt =>
      cases hnt with
      | intro G hG =>
          exists nt
          exists ReverseGrammar G
          constructor
          · exact rightRegular_reverseGrammar_leftRegular hG.left
          · intro w
            constructor
            · intro hw
              have hrev :=
                (reverseGrammar_language_exact G w).mp hw
              exact (hG.right (Word.Reverse w)).mp hrev
            · intro hw
              exact (reverseGrammar_language_exact G w).mpr
                ((hG.right (Word.Reverse w)).mpr hw)

theorem leftRegularLanguage_iff_reverse_rightRegular {L : Language terminal} :
    LeftRegularLanguage L <-> RightRegularLanguage (Language.Reverse L) := by
  constructor
  · exact leftRegularLanguage_reverse_rightRegular
  · intro hRev
    cases rightRegularLanguage_reverse_leftRegular hRev with
    | intro nt hnt =>
        cases hnt with
        | intro G hG =>
            exists nt
            exists G
            constructor
            · exact hG.left
            · intro w
              constructor
              · intro hw
                have hrr := (hG.right w).mp hw
                change Word.Reverse (Word.Reverse w) ∈ L at hrr
                simpa [Word.Reverse, List.reverse_reverse] using hrr
              · intro hw
                apply (hG.right w).mpr
                change Word.Reverse (Word.Reverse w) ∈ L
                simpa [Word.Reverse, List.reverse_reverse] using hw

theorem rightRegularLanguage_regular (alphabet : List terminal)
    (halphabet : forall a, a ∈ alphabet) {L : Language terminal}
    (hL : RightRegularLanguage L) :
    Languages.RegularLanguage.Regular L := by
  cases hL with
  | intro nt hnt =>
      cases hnt with
      | intro G hG =>
          have hReg :
              Languages.RegularLanguage.Regular
                (NFA.AcceptedLanguage (RightRegularNFA G)) :=
            Languages.RegularLanguage.nfa_language_regular alphabet halphabet
              (RightRegularNFA G)
          cases hReg with
          | intro r hr =>
              exists r
              exact Language.equal_trans hr
                (Language.equal_trans
                  (Language.equal_symm (rightRegularNFA_language_exact G hG.left))
                  hG.right)

theorem leftRegularLanguage_regular (alphabet : List terminal)
    (halphabet : forall a, a ∈ alphabet) {L : Language terminal}
    (hL : LeftRegularLanguage L) :
    Languages.RegularLanguage.Regular L := by
  have hRevRight : RightRegularLanguage (Language.Reverse L) :=
    leftRegularLanguage_reverse_rightRegular hL
  have hRevReg :
      Languages.RegularLanguage.Regular (Language.Reverse L) :=
    rightRegularLanguage_regular alphabet halphabet hRevRight
  have hDouble :
      Languages.RegularLanguage.Regular
        (Language.Reverse (Language.Reverse L)) :=
    Languages.RegularLanguage.reverse_regular hRevReg
  cases hDouble with
  | intro r hr =>
      exists r
      intro w
      constructor
      · intro hw
        have hmem := (hr w).mp hw
        change Word.Reverse (Word.Reverse w) ∈ L at hmem
        simpa [Word.Reverse, List.reverse_reverse] using hmem
      · intro hw
        apply (hr w).mpr
        change Word.Reverse (Word.Reverse w) ∈ L
        simpa [Word.Reverse, List.reverse_reverse] using hw

/-!
The reverse construction turns an NFA into a right-regular grammar. Transitions
become terminal-then-state productions, accepting states get empty productions,
and the generated language is later shown to be exactly the NFA language.
-/

def NFARightRegularProduces (M : NFA terminal state) :
    state -> SententialForm terminal state -> Prop
  | q, [] => M.accept q
  | q, [Symbol.nonterminal r] => r ∈ M.step q none
  | q, [Symbol.terminal a, Symbol.nonterminal r] => r ∈ M.step q (some a)
  | _, _ => False

def NFARightRegularGrammar (M : NFA terminal state) : CFG terminal state where
  start := M.start
  produces := NFARightRegularProduces M
  nonterminalsFinite := M.statesFinite

def NFASymbolLanguage (M : NFA terminal state) :
    Symbol terminal state -> Language terminal
  | Symbol.terminal a => Language.Singleton (Word.Symbol a)
  | Symbol.nonterminal q => AcceptedFrom M q

theorem nfaRightRegularGrammar_rightRegular (M : NFA terminal state) :
    RightRegular (NFARightRegularGrammar M) := by
  intro q rhs hprod
  cases rhs with
  | nil =>
      exact RightRegularRHS.epsilon
  | cons first rest =>
      cases first with
      | terminal a =>
          cases rest with
          | nil =>
              cases hprod
          | cons second rest' =>
              cases second with
              | terminal b =>
                  cases rest' <;> cases hprod
              | nonterminal r =>
                  cases rest' with
                  | nil =>
                      exact RightRegularRHS.terminalThenNonterminal a r
                  | cons s tail =>
                      cases hprod
      | nonterminal r =>
          cases rest with
          | nil =>
              exact RightRegularRHS.nonterminal r
          | cons s tail =>
              cases hprod

theorem nfaRightRegular_path_derives (M : NFA terminal state)
    {q r : state} {w : Word terminal}
    (hpath : NFA.Path M q w r) :
    Derives (NFARightRegularGrammar M) [Symbol.nonterminal q]
      (SententialForm.terminalWord w ++ [Symbol.nonterminal r]) := by
  induction hpath with
  | nil q =>
      exact Derives.refl _
  | eps hstep _htail ih =>
      rename_i q r _s _tail
      have hYield : Yields (NFARightRegularGrammar M)
          [Symbol.nonterminal q] [Symbol.nonterminal r] := by
        exists []
        exists []
        exists q
        exists [Symbol.nonterminal r]
      exact derives_trans (yields_derives hYield) ih
  | sym hstep _htail ih =>
      rename_i q r s a tail
      have hYield : Yields (NFARightRegularGrammar M)
          [Symbol.nonterminal q] [Symbol.terminal a, Symbol.nonterminal r] := by
        exists []
        exists []
        exists q
        exists [Symbol.terminal a, Symbol.nonterminal r]
      have hPrefix : Derives (NFARightRegularGrammar M) [Symbol.nonterminal q]
          [Symbol.terminal a, Symbol.nonterminal r] :=
        yields_derives hYield
      have hTail : Derives (NFARightRegularGrammar M)
          [Symbol.terminal a, Symbol.nonterminal r]
          (Symbol.terminal a ::
            (SententialForm.terminalWord tail ++ [Symbol.nonterminal s])) := by
        simpa using derives_context ih [Symbol.terminal a] []
      have hAll := derives_trans hPrefix hTail
      simpa [SententialForm.terminalWord] using hAll

theorem nfaRightRegular_accepts_to_generates (M : NFA terminal state)
    {w : Word terminal}
    (h : w ∈ NFA.AcceptedLanguage M) :
    w ∈ GeneratedLanguage (NFARightRegularGrammar M) := by
  cases (NFA.pathAccepts_iff_accepts M w).mpr h with
  | intro q hq =>
      have hPrefix := nfaRightRegular_path_derives M hq.left
      have hFinalYield : Yields (NFARightRegularGrammar M)
          (SententialForm.terminalWord w ++ [Symbol.nonterminal q])
          (SententialForm.terminalWord w) := by
        have hLocal : Yields (NFARightRegularGrammar M)
            [Symbol.nonterminal q] [] := by
          exists []
          exists []
          exists q
          exists ([] : SententialForm terminal state)
          constructor
          · exact hq.right
          constructor <;> rfl
        simpa using yields_context hLocal (SententialForm.terminalWord w) []
      exact derives_trans hPrefix (yields_derives hFinalYield)

/-!
Soundness for the NFA-derived grammar interprets each production as one NFA
move, or as acceptance when the production is empty. This is the local step that
lets generated derivations collapse back to automaton paths.
-/

theorem nfaRightRegular_production_sound (M : NFA terminal state)
    {q : state} {rhs : SententialForm terminal state}
    (hprod : (NFARightRegularGrammar M).produces q rhs) :
    forall w, w ∈ FormLanguage (NFASymbolLanguage M) rhs ->
      w ∈ AcceptedFrom M q := by
  intro w hw
  cases nfaRightRegularGrammar_rightRegular M q rhs hprod with
  | epsilon =>
      cases hw
      exists q
      constructor
      · exact NFA.Path.nil q
      · exact hprod
  | nonterminal r =>
      cases hw with
      | intro first hfirst =>
          cases hfirst with
          | intro tail htail =>
              cases htail.right.left
              rw [htail.right.right, Word.concat_empty_right]
              cases htail.left with
              | intro s hs =>
                  exists s
                  constructor
                  · exact NFA.Path.eps hprod hs.left
                  · exact hs.right
  | terminalThenNonterminal a r =>
      cases hw with
      | intro first hfirst =>
          cases hfirst with
          | intro tail htail =>
              have hfirst : first = Word.Symbol a := htail.left
              rw [htail.right.right, hfirst]
              cases htail.right.left with
              | intro middle hmiddle =>
                  cases hmiddle with
                  | intro rest hrest =>
                    cases hrest.right.left
                    rw [hrest.right.right, Word.concat_empty_right]
                    cases hrest.left with
                    | intro s hs =>
                      exists s
                      constructor
                      · exact NFA.Path.sym hprod hs.left
                      · exact hs.right

theorem nfaRightRegular_yields_sound (M : NFA terminal state)
    {x y : SententialForm terminal state} {w : Word terminal}
    (h : Yields (NFARightRegularGrammar M) x y)
    (hw : w ∈ FormLanguage (NFASymbolLanguage M) y) :
    w ∈ FormLanguage (NFASymbolLanguage M) x := by
  cases h with
  | intro u hu =>
      cases hu with
      | intro v hv =>
          cases hv with
          | intro A hA =>
              cases hA with
              | intro rhs hrhs =>
                  cases hrhs with
                  | intro hprod hrest =>
                      cases hrest with
                      | intro hx hy =>
                          rw [hy] at hw
                          rw [hx]
                          exact formLanguage_replace_sound
                            (NFASymbolLanguage M)
                            (nfaRightRegular_production_sound M hprod)
                            hw

theorem nfaRightRegular_derives_sound (M : NFA terminal state)
    {x y : SententialForm terminal state} {w : Word terminal}
    (h : Derives (NFARightRegularGrammar M) x y)
    (hw : w ∈ FormLanguage (NFASymbolLanguage M) y) :
    w ∈ FormLanguage (NFASymbolLanguage M) x := by
  induction h with
  | refl _ =>
      exact hw
  | step hstep _ ih =>
      exact nfaRightRegular_yields_sound M hstep (ih hw)

theorem nfaRightRegular_generates_to_accepts (M : NFA terminal state)
    {w : Word terminal}
    (h : w ∈ GeneratedLanguage (NFARightRegularGrammar M)) :
    w ∈ NFA.AcceptedLanguage M := by
  have hterminal : w ∈ FormLanguage (NFASymbolLanguage M)
      (SententialForm.terminalWord (nt := state) w) :=
    terminalWord_mem_formLanguage (NFASymbolLanguage M) (by intro a; rfl) w
  have hsound := nfaRightRegular_derives_sound M h hterminal
  cases hsound with
  | intro first hfirst =>
      cases hfirst with
      | intro tail htail =>
          cases htail.right.left
          exact (NFA.pathAccepts_iff_accepts M w).mp (by
            rw [htail.right.right, Word.concat_empty_right]
            exact htail.left)

theorem nfaRightRegularGrammar_language_exact (M : NFA terminal state) :
    Language.Equal (GeneratedLanguage (NFARightRegularGrammar M))
      (NFA.AcceptedLanguage M) := by
  intro w
  constructor
  · exact nfaRightRegular_generates_to_accepts M
  · exact nfaRightRegular_accepts_to_generates M

theorem nfa_rightRegularLanguage {state : Type} (M : NFA terminal state) :
    RightRegularLanguage (NFA.AcceptedLanguage M) := by
  exists state
  exists NFARightRegularGrammar M
  constructor
  · exact nfaRightRegularGrammar_rightRegular M
  · exact nfaRightRegularGrammar_language_exact M

theorem regular_rightRegularLanguage {L : Language terminal}
    (hL : Languages.RegularLanguage.Regular L) :
    RightRegularLanguage L := by
  cases Languages.RegularLanguage.regular_is_nfa_recognizable hL with
  | intro state hstate =>
      cases hstate with
      | intro M hM =>
          exists state
          exists NFARightRegularGrammar M
          constructor
          · exact nfaRightRegularGrammar_rightRegular M
          · exact Language.equal_trans (nfaRightRegularGrammar_language_exact M) hM

theorem regular_leftRegularLanguage {L : Language terminal}
    (hL : Languages.RegularLanguage.Regular L) :
    LeftRegularLanguage L :=
  leftRegularLanguage_iff_reverse_rightRegular.mpr
    (regular_rightRegularLanguage
      (Languages.RegularLanguage.reverse_regular hL))

theorem regular_iff_rightRegularLanguage (alphabet : List terminal)
    (halphabet : forall a, a ∈ alphabet) {L : Language terminal} :
    Languages.RegularLanguage.Regular L <-> RightRegularLanguage L := by
  constructor
  · exact regular_rightRegularLanguage
  · exact rightRegularLanguage_regular alphabet halphabet

theorem regular_iff_leftRegularLanguage (alphabet : List terminal)
    (halphabet : forall a, a ∈ alphabet) {L : Language terminal} :
    Languages.RegularLanguage.Regular L <-> LeftRegularLanguage L := by
  constructor
  · exact regular_leftRegularLanguage
  · exact leftRegularLanguage_regular alphabet halphabet

end CFG

end Grammars
end FoC
