import FoC.Computability.Compiler.DescriptionExecution
import FoC.Computability.Compiler.Core.TransitionTableChecks

set_option doc.verso true

/-!
# Certified finite transducer core

This module starts the reusable finite-transducer layer used by exact
machine-description construction proofs.  It intentionally separates the pure
left-to-right transducer semantics from the later compiler to machine
descriptions, so field-rewrite proofs can first state and test their
Boolean-word behavior without committing to a transition-table layout.
-/

namespace FoC
namespace Computability

open Languages
open MachineDescription

namespace CommonGround
namespace FiniteTransducers

/--
A deterministic one-way Boolean finite transducer.  The current input symbol is
{lean}`none` at the physical blank following the input word; otherwise it is the
current Boolean cell.  A transition emits a finite Boolean word and advances to
the next input cell.
-/
structure FiniteTransducer where
  stateCount : Nat
  start : Nat
  halt : Nat
  step : Nat -> Option Bool -> Option (Nat × Word Bool)

def readSymbols : List (Option Bool) :=
  [none, some false, some true]

theorem mem_readSymbols (read : Option Bool) :
    read ∈ readSymbols := by
  cases read with
  | none =>
      simp [readSymbols]
  | some bit =>
      cases bit <;> simp [readSymbols]

/-- One pure transition row in the finite-transducer table. -/
structure TransitionRow where
  source : Nat
  read : Option Bool
  target : Nat
  emitted : Word Bool

namespace TransitionRow

/--
Lower an empty-emission row to a preserving scanner transition.  This is the
first constrained transition lowering used by the compiler skeleton.
-/
def toPreservingScanTransition? (row : TransitionRow) :
    Option TransitionDescription :=
  match row.emitted with
  | [] =>
    some
      { source := row.source
        read := row.read
        write := row.read
        move := Direction.right
        target := row.target }
  | _ :: _ => none

/--
Lower the first erasing-emitter subset: nonblank input transitions must emit
nothing and are compiled as erase-and-move-right transitions; the trailing blank
transition must emit exactly one bit and is compiled as the final write.
-/
def toEraseThenEmitBitTransition? (row : TransitionRow) :
    Option TransitionDescription :=
  match row.read, row.emitted with
  | some _, [] =>
      some
        { source := row.source
          read := row.read
          write := none
          move := Direction.right
          target := row.target }
  | none, [bit] =>
      some
        { source := row.source
          read := row.read
          write := some bit
          move := Direction.right
          target := row.target }
  | _, _ => none

/--
Entry transition lowering for the state-expanding copy-and-append-four-bits
compiler slice.  The scan rows preserve input bits; the blank row writes the
first emitted bit and enters the generated writer states.
-/
def toCopyAppendFourEntryTransition? (row : TransitionRow) :
    Option TransitionDescription :=
  match row.read, row.emitted with
  | some false, [false] =>
      some
        { source := row.source
          read := row.read
          write := row.read
          move := Direction.right
          target := row.target }
  | some true, [true] =>
      some
        { source := row.source
          read := row.read
          write := row.read
          move := Direction.right
          target := row.target }
  | none, [b0, _b1, _b2, _b3] =>
      some
        { source := row.source
          read := none
          write := some b0
          move := Direction.right
          target := 1 }
  | _, _ => none

/--
Continuation transitions for the fixed four-bit writer.  These states are
generated by the compiler rather than present in the source transducer.
-/
def toCopyAppendFourContinuationTransitions? (row : TransitionRow) :
    Option (List TransitionDescription) :=
  match row.read, row.emitted with
  | none, [_b0, b1, b2, b3] =>
      some
        [ { source := 1
            read := none
            write := some b1
            move := Direction.right
            target := 2 }
        , { source := 2
            read := none
            write := some b2
            move := Direction.right
            target := 3 }
        , { source := 3
            read := none
            write := some b3
            move := Direction.right
            target := 4 } ]
  | _, _ => none

end TransitionRow

namespace FiniteTransducer

def rowsForState (F : FiniteTransducer) (state : Nat) :
    List TransitionRow :=
  readSymbols.filterMap (fun read =>
    match F.step state read with
    | none => none
    | some (target, emitted) =>
        some
          { source := state
            read := read
            target := target
            emitted := emitted })

def transitionRows (F : FiniteTransducer) : List TransitionRow :=
  ((List.range F.stateCount).map F.rowsForState).flatten

def preservingScanTransitions
    (F : FiniteTransducer) : List TransitionDescription :=
  F.transitionRows.filterMap TransitionRow.toPreservingScanTransition?

def preservingScanDescription
    (F : FiniteTransducer) : MachineDescription where
  stateCount := F.stateCount
  start := F.start
  halt := F.halt
  transitions := F.preservingScanTransitions

def eraseThenEmitBitTransitions
    (F : FiniteTransducer) : List TransitionDescription :=
  F.transitionRows.filterMap TransitionRow.toEraseThenEmitBitTransition?

def eraseThenEmitBitDescription
    (F : FiniteTransducer) : MachineDescription where
  stateCount := F.stateCount
  start := F.start
  halt := F.halt
  transitions := F.eraseThenEmitBitTransitions

def copyAppendFourTransitions
    (F : FiniteTransducer) : List TransitionDescription :=
  List.append
    (F.transitionRows.filterMap
      TransitionRow.toCopyAppendFourEntryTransition?)
    ((F.transitionRows.filterMap
      TransitionRow.toCopyAppendFourContinuationTransitions?).flatten)

def copyAppendWordHalt (final : Word Bool) : Nat :=
  match final with
  | [] => 1
  | _ :: _ => final.length

def copyAppendWordWriteTransitionsFrom
    (source halt : Nat) : Word Bool -> List TransitionDescription
  | [] => []
  | bit :: rest =>
      { source := source
        read := none
        write := some bit
        move := Direction.right
        target :=
          match rest with
          | [] => halt
          | _ :: _ => source + 1 } ::
        copyAppendWordWriteTransitionsFrom (source + 1) halt rest

def copyAppendWordScanFalseTransition : TransitionDescription :=
  { source := 0
    read := some false
    write := some false
    move := Direction.right
    target := 0 }

def copyAppendWordScanTrueTransition : TransitionDescription :=
  { source := 0
    read := some true
    write := some true
    move := Direction.right
    target := 0 }

def copyAppendWordTransitions
    (final : Word Bool) : List TransitionDescription :=
  match copyAppendWordWriteTransitionsFrom 0 (copyAppendWordHalt final) final with
  | [] =>
      [ { source := 0
          read := none
          write := none
          move := Direction.right
          target := copyAppendWordHalt final }
      , copyAppendWordScanFalseTransition
      , copyAppendWordScanTrueTransition ]
  | first :: rest =>
      first :: copyAppendWordScanFalseTransition ::
        copyAppendWordScanTrueTransition :: rest

theorem copyAppendWordWriteTransitionsFrom_source_bounds
    (source halt : Nat) (final : Word Bool) :
    forall t : TransitionDescription,
      t ∈ copyAppendWordWriteTransitionsFrom source halt final ->
        source ≤ t.source ∧ t.source < source + final.length := by
  induction final generalizing source with
  | nil =>
      intro t ht
      simp [copyAppendWordWriteTransitionsFrom] at ht
  | cons _bit rest ih =>
      intro t ht
      simp [copyAppendWordWriteTransitionsFrom] at ht
      rcases ht with ht | ht
      · subst t
        constructor <;> simp
      · have htail := ih (source + 1) t ht
        constructor
        · omega
        · simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
            htail.right

theorem copyAppendWordWriteTransitionsFrom_wellFormed
    (source : Nat) (final : Word Bool) :
    forall t : TransitionDescription,
      t ∈ copyAppendWordWriteTransitionsFrom
          source (source + final.length) final ->
        TransitionDescription.WellFormed (source + final.length + 1) t := by
  induction final generalizing source with
  | nil =>
      intro t ht
      simp [copyAppendWordWriteTransitionsFrom] at ht
  | cons _bit rest ih =>
      intro t ht
      simp [copyAppendWordWriteTransitionsFrom] at ht
      rcases ht with ht | ht
      · subst t
        constructor
        · simp
          omega
        · cases rest <;> simp <;> omega
      · have htail := ih (source + 1) t
          (by
            simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using ht)
        simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using htail

theorem copyAppendWordWriteTransitionsFrom_deterministic
    (source : Nat) (final : Word Bool) :
    forall t u : TransitionDescription,
      t ∈ copyAppendWordWriteTransitionsFrom
          source (source + final.length) final ->
      u ∈ copyAppendWordWriteTransitionsFrom
          source (source + final.length) final ->
      TransitionDescription.SameKey t u ->
        TransitionDescription.SameAction t u := by
  induction final generalizing source with
  | nil =>
      intro t _u ht _hu _hkey
      simp [copyAppendWordWriteTransitionsFrom] at ht
  | cons bit rest ih =>
      intro t u ht hu hkey
      simp [copyAppendWordWriteTransitionsFrom] at ht hu
      rcases ht with ht | ht <;> rcases hu with hu | hu
      · subst t
        subst u
        simp [TransitionDescription.SameAction]
      · subst t
        have hubounds :=
          copyAppendWordWriteTransitionsFrom_source_bounds (source + 1)
            (source + (bit :: rest).length) rest u hu
        have husource : u.source = source := hkey.left.symm
        omega
      · subst u
        have htbounds :=
          copyAppendWordWriteTransitionsFrom_source_bounds (source + 1)
            (source + (bit :: rest).length) rest t ht
        have htsource : t.source = source := hkey.left
        omega
      · exact ih (source + 1) t u
          (by
            simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using ht)
          (by
            simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using hu)
          hkey

/-- Basic bounded-state side conditions for generated machines. -/
def WellFormed (F : FiniteTransducer) : Prop :=
  0 < F.stateCount ∧
    F.start < F.stateCount ∧
    F.halt < F.stateCount ∧
      forall state read next out,
        F.step state read = some (next, out) ->
          next < F.stateCount

/--
Fuelled executable semantics.  Each nonhalting step consumes one input cell, or
the trailing blank when the input word is empty.
-/
def run (F : FiniteTransducer) :
    Nat -> Nat -> Word Bool -> Option (Nat × Word Bool)
  | 0, state, _input =>
      if state = F.halt then
        some (F.halt, [])
      else
        none
  | fuel + 1, state, input =>
      if state = F.halt then
        some (F.halt, [])
      else
        let read : Option Bool :=
          match input with
          | [] => none
          | bit :: _rest => some bit
        let rest : Word Bool :=
          match input with
          | [] => []
          | _bit :: rest => rest
        match F.step state read with
        | none => none
        | some (next, emitted) =>
            if next = F.halt then
              some (next, emitted)
            else
              match F.run fuel next rest with
              | none => none
              | some (final, output) =>
                  some (final, List.append emitted output)

def runFromStart
    (F : FiniteTransducer) (fuel : Nat) (input : Word Bool) :
    Option (Nat × Word Bool) :=
  F.run fuel F.start input

/--
The default left-to-right contract: one transition for every input bit, plus
one final transition on the trailing blank.
-/
def RunsToOutput
    (F : FiniteTransducer) (input output : Word Bool) : Prop :=
  F.runFromStart (input.length + 1) input = some (F.halt, output)

@[simp] theorem run_halt
    (F : FiniteTransducer) (fuel : Nat) (input : Word Bool) :
    F.run fuel F.halt input = some (F.halt, []) := by
  cases fuel <;> simp [run] <;> rfl

theorem RunsToOutput_unique
    {F : FiniteTransducer} {input out₁ out₂ : Word Bool}
    (h₁ : F.RunsToOutput input out₁)
    (h₂ : F.RunsToOutput input out₂) :
    out₁ = out₂ := by
  unfold RunsToOutput at h₁ h₂
  rw [h₁] at h₂
  cases h₂
  rfl

end FiniteTransducer

def tapeAtCells
    (leftRev cells : List (Option Bool)) : Tape Bool :=
  match cells with
  | [] => { left := leftRev, head := none, right := [] }
  | cell :: rest => { left := leftRev, head := cell, right := rest }

def inputWithTrailingBlankPadding
    (w : Word Bool) (padding : Nat) : Tape Bool :=
  match w with
  | [] =>
      { left := []
        head := none
        right := List.replicate padding none }
  | bit :: rest =>
      { left := []
        head := some bit
        right := List.append (rest.map some)
          (List.replicate padding none) }

/--
Source tape for the generic transducer contract.  The left context is reserved
blank scratch; the head is on the first input bit, or on the trailing blank when
the input is empty.
-/
def FSTSourceTape
    (input : Word Bool) (leftScratch : Nat) : Tape Bool :=
  tapeAtCells (List.replicate leftScratch (none : Option Bool))
    (List.append (input.map some) [none])

/--
Right-shifted scratch-padded target tape.  This mirrors the padded emitter
shape used by encoded rewriter components, without importing those higher-level
modules into this lower-level module.
-/
def FSTTargetTape
    (output : Word Bool) (scratchWidth : Nat) : Tape Bool :=
  Tape.move Direction.right
    (inputWithTrailingBlankPadding output scratchWidth)

def FSTRightAppendedTargetTape
    (output : Word Bool) (leftScratch : Nat) : Tape Bool :=
  tapeAtCells
    (List.append (output.reverse.map some)
      (List.replicate leftScratch (none : Option Bool)))
    []

theorem tapeAtCells_normalizedOutput
    (leftRev cells : List (Option Bool)) :
    Tape.normalizedOutput (tapeAtCells leftRev cells) =
      (List.append leftRev.reverse cells).filterMap (fun cell => cell) := by
  cases cells <;>
    simp [tapeAtCells, Tape.normalizedOutput, Tape.cells]

theorem inputWithTrailingBlankPadding_normalizedOutput
    (w : Word Bool) (padding : Nat) :
    Tape.normalizedOutput
        (inputWithTrailingBlankPadding w padding) = w := by
  cases w <;>
    simp [inputWithTrailingBlankPadding, Tape.normalizedOutput,
      Tape.cells, Function.comp_def, List.filterMap_append]

theorem FSTSourceTape_normalizedOutput
    (input : Word Bool) (leftScratch : Nat) :
    Tape.normalizedOutput (FSTSourceTape input leftScratch) = input := by
  rw [FSTSourceTape, tapeAtCells_normalizedOutput]
  simp [Function.comp_def, List.filterMap_append]

theorem FSTTargetTape_normalizedOutput
    (output : Word Bool) (scratchWidth : Nat) :
    Tape.normalizedOutput (FSTTargetTape output scratchWidth) =
      output := by
  rw [FSTTargetTape]
  rw [Tape.normalizedOutput_move]
  exact inputWithTrailingBlankPadding_normalizedOutput output scratchWidth

theorem FSTRightAppendedTargetTape_normalizedOutput
    (output : Word Bool) (leftScratch : Nat) :
    Tape.normalizedOutput
        (FSTRightAppendedTargetTape output leftScratch) =
      output := by
  rw [FSTRightAppendedTargetTape, tapeAtCells_normalizedOutput]
  simp [Function.comp_def, List.filterMap_append]

/-- Transducer that copies every input bit and halts at the trailing blank. -/
def identityTransducer : FiniteTransducer where
  stateCount := 2
  start := 0
  halt := 1
  step := fun state read =>
    match state, read with
    | 0, some bit => some (0, [bit])
    | 0, none => some (1, [])
    | _, _ => none

theorem identityTransducer_wellFormed :
    identityTransducer.WellFormed := by
  refine ⟨by decide, by decide, by decide, ?_⟩
  intro state read next out hstep
  cases state <;> cases read <;>
    simp [identityTransducer] at hstep
  · rcases hstep with ⟨hnext, _hout⟩
    rw [← hnext]
    decide
  · rcases hstep with ⟨hnext, _hout⟩
    rw [← hnext]
    decide

theorem identityTransducer_run
    (input : Word Bool) :
    identityTransducer.runFromStart (input.length + 1) input =
      some (identityTransducer.halt, input) := by
  induction input with
  | nil =>
      simp [FiniteTransducer.runFromStart, FiniteTransducer.run,
        identityTransducer]
  | cons bit rest ih =>
      rw [show (bit :: rest).length + 1 = (rest.length + 1) + 1 by
        simp]
      change
        (match identityTransducer.runFromStart (rest.length + 1) rest with
        | none => none
        | some (final, output) =>
            some (final, List.append [bit] output)) =
          some (identityTransducer.halt, bit :: rest)
      rw [ih]
      rfl

theorem identityTransducer_runsToOutput
    (input : Word Bool) :
    identityTransducer.RunsToOutput input input := by
  exact identityTransducer_run input

def identityPreservingScanDescription : MachineDescription :=
  identityTransducer.preservingScanDescription

theorem identityPreservingScanDescription_wellFormed :
    identityPreservingScanDescription.WellFormed := by
  refine ⟨by decide, by decide, by decide, ?_, ?_⟩
  · exact transition_wellFormed_of_all
      (l := identityPreservingScanDescription.transitions)
      (stateCount := identityPreservingScanDescription.stateCount)
      (by native_decide)
  · exact transition_deterministic_of_all
      (l := identityPreservingScanDescription.transitions)
      (by native_decide)

theorem identityPreservingScanDescription_haltTransitionFree :
    identityPreservingScanDescription.HaltTransitionFree := by
  exact transition_notFrom_of_all
    (l := identityPreservingScanDescription.transitions)
    (state := identityPreservingScanDescription.halt)
    (by native_decide)

theorem identityPreservingScanDescription_subroutineReady :
    identityPreservingScanDescription.SubroutineReady :=
  ⟨identityPreservingScanDescription_wellFormed,
    identityPreservingScanDescription_haltTransitionFree⟩

/-- Transducer that consumes the input and emits the empty word. -/
def eraseTransducer : FiniteTransducer where
  stateCount := 2
  start := 0
  halt := 1
  step := fun state read =>
    match state, read with
    | 0, some _bit => some (0, [])
    | 0, none => some (1, [])
    | _, _ => none

theorem eraseTransducer_wellFormed :
    eraseTransducer.WellFormed := by
  refine ⟨by decide, by decide, by decide, ?_⟩
  intro state read next out hstep
  cases state <;> cases read <;>
    simp [eraseTransducer] at hstep
  · rcases hstep with ⟨hnext, _hout⟩
    rw [← hnext]
    decide
  · rcases hstep with ⟨hnext, _hout⟩
    rw [← hnext]
    decide

theorem eraseTransducer_run
    (input : Word Bool) :
    eraseTransducer.runFromStart (input.length + 1) input =
      some (eraseTransducer.halt, []) := by
  induction input with
  | nil =>
      rfl
  | cons bit rest ih =>
      rw [show (bit :: rest).length + 1 = (rest.length + 1) + 1 by
        simp]
      change
        (match eraseTransducer.runFromStart (rest.length + 1) rest with
        | none => none
        | some (final, output) =>
            some (final, List.append ([] : List Bool) output)) =
          some (eraseTransducer.halt, [])
      rw [ih]
      rfl

theorem eraseTransducer_runsToOutput
    (input : Word Bool) :
    eraseTransducer.RunsToOutput input [] := by
  exact eraseTransducer_run input

/--
Transducer that consumes the input, ignores all input bits, and emits one
Boolean bit when it reaches the trailing blank.
-/
def constantBitTransducer (out : Bool) : FiniteTransducer where
  stateCount := 2
  start := 0
  halt := 1
  step := fun state read =>
    match state, read with
    | 0, some _bit => some (0, [])
    | 0, none => some (1, [out])
    | _, _ => none

theorem constantBitTransducer_wellFormed
    (out : Bool) :
    (constantBitTransducer out).WellFormed := by
  refine ⟨by simp [constantBitTransducer],
    by simp [constantBitTransducer],
    by simp [constantBitTransducer], ?_⟩
  intro state read next emitted hstep
  cases state <;> cases read <;>
    simp [constantBitTransducer] at hstep
  · rcases hstep with ⟨hnext, _hemitted⟩
    rw [← hnext]
    simp [constantBitTransducer]
  · rcases hstep with ⟨hnext, _hemitted⟩
    rw [← hnext]
    simp [constantBitTransducer]

theorem constantBitTransducer_run
    (out : Bool) (input : Word Bool) :
    (constantBitTransducer out).runFromStart
        (input.length + 1) input =
      some ((constantBitTransducer out).halt, [out]) := by
  induction input with
  | nil =>
      rfl
  | cons bit rest ih =>
      rw [show (bit :: rest).length + 1 = (rest.length + 1) + 1 by
        simp]
      change
        (match
          (constantBitTransducer out).runFromStart
            (rest.length + 1) rest with
        | none => none
        | some (final, output) =>
            some (final, List.append ([] : List Bool) output)) =
          some ((constantBitTransducer out).halt, [out])
      rw [ih]
      rfl

theorem constantBitTransducer_runsToOutput
    (out : Bool) (input : Word Bool) :
    (constantBitTransducer out).RunsToOutput input [out] := by
  exact constantBitTransducer_run out input

/--
A one-state transducer that emits a word for every input bit and emits a final
word when it reaches the trailing blank.
-/
def bitwiseOutput
    (emit : Bool -> Word Bool) : Word Bool -> Word Bool
  | [] => []
  | bit :: rest => List.append (emit bit) (bitwiseOutput emit rest)

def bitwiseOutputTransducer
    (emit : Bool -> Word Bool) (final : Word Bool) :
    FiniteTransducer where
  stateCount := 2
  start := 0
  halt := 1
  step := fun state read =>
    match state, read with
    | 0, some bit => some (0, emit bit)
    | 0, none => some (1, final)
    | _, _ => none

theorem bitwiseOutputTransducer_wellFormed
    (emit : Bool -> Word Bool) (final : Word Bool) :
    (bitwiseOutputTransducer emit final).WellFormed := by
  refine ⟨by simp [bitwiseOutputTransducer],
    by simp [bitwiseOutputTransducer],
    by simp [bitwiseOutputTransducer], ?_⟩
  intro state read next emitted hstep
  cases state with
  | zero =>
      cases read with
      | none =>
          simp [bitwiseOutputTransducer] at hstep
          rcases hstep with ⟨hnext, _hemitted⟩
          rw [← hnext]
          simp [bitwiseOutputTransducer]
      | some bit =>
          cases bit <;>
            simp [bitwiseOutputTransducer] at hstep
          · rcases hstep with ⟨hnext, _hemitted⟩
            rw [← hnext]
            simp [bitwiseOutputTransducer]
          · rcases hstep with ⟨hnext, _hemitted⟩
            rw [← hnext]
            simp [bitwiseOutputTransducer]
  | succ state =>
      cases read <;>
        simp [bitwiseOutputTransducer] at hstep

theorem bitwiseOutputTransducer_run
    (emit : Bool -> Word Bool) (final input : Word Bool) :
    (bitwiseOutputTransducer emit final).runFromStart
        (input.length + 1) input =
      some ((bitwiseOutputTransducer emit final).halt,
        List.append (bitwiseOutput emit input) final) := by
  induction input with
  | nil =>
      rfl
  | cons bit rest ih =>
      rw [show (bit :: rest).length + 1 = (rest.length + 1) + 1 by
        simp]
      change
        (match
          (bitwiseOutputTransducer emit final).runFromStart
            (rest.length + 1) rest with
        | none => none
        | some (finalState, output) =>
            some (finalState, List.append (emit bit) output)) =
          some ((bitwiseOutputTransducer emit final).halt,
            List.append (bitwiseOutput emit (bit :: rest)) final)
      rw [ih]
      simp [bitwiseOutput, List.append_assoc]

theorem bitwiseOutputTransducer_runsToOutput
    (emit : Bool -> Word Bool) (final input : Word Bool) :
    (bitwiseOutputTransducer emit final).RunsToOutput input
      (List.append (bitwiseOutput emit input) final) := by
  exact bitwiseOutputTransducer_run emit final input

theorem bitwiseOutput_singleton
    (input : Word Bool) :
    bitwiseOutput (fun bit => [bit]) input = input := by
  induction input with
  | nil =>
      rfl
  | cons bit rest ih =>
      simp [bitwiseOutput, ih]

def appendFinalWordTransducer
    (final : Word Bool) : FiniteTransducer :=
  bitwiseOutputTransducer (fun bit => [bit]) final

theorem appendFinalWordTransducer_wellFormed
    (final : Word Bool) :
    (appendFinalWordTransducer final).WellFormed := by
  exact bitwiseOutputTransducer_wellFormed (fun bit => [bit]) final

theorem appendFinalWordTransducer_run
    (final input : Word Bool) :
    (appendFinalWordTransducer final).runFromStart
        (input.length + 1) input =
      some ((appendFinalWordTransducer final).halt,
        List.append input final) := by
  rw [appendFinalWordTransducer, bitwiseOutputTransducer_run,
    bitwiseOutput_singleton]

theorem appendFinalWordTransducer_runsToOutput
    (final input : Word Bool) :
    (appendFinalWordTransducer final).RunsToOutput
      input (List.append input final) := by
  exact appendFinalWordTransducer_run final input

def appendFixedFourBitsTransducer
    (b0 b1 b2 b3 : Bool) : FiniteTransducer :=
  appendFinalWordTransducer [b0, b1, b2, b3]

theorem appendFixedFourBitsTransducer_wellFormed
    (b0 b1 b2 b3 : Bool) :
    (appendFixedFourBitsTransducer b0 b1 b2 b3).WellFormed := by
  exact appendFinalWordTransducer_wellFormed [b0, b1, b2, b3]

theorem appendFixedFourBitsTransducer_run
    (b0 b1 b2 b3 : Bool) (input : Word Bool) :
    (appendFixedFourBitsTransducer b0 b1 b2 b3).runFromStart
        (input.length + 1) input =
      some ((appendFixedFourBitsTransducer b0 b1 b2 b3).halt,
        List.append input [b0, b1, b2, b3]) := by
  exact appendFinalWordTransducer_run [b0, b1, b2, b3] input

theorem appendFixedFourBitsTransducer_runsToOutput
    (b0 b1 b2 b3 : Bool) (input : Word Bool) :
    (appendFixedFourBitsTransducer b0 b1 b2 b3).RunsToOutput
      input (List.append input [b0, b1, b2, b3]) := by
  exact appendFixedFourBitsTransducer_run b0 b1 b2 b3 input

def FSTScanTargetTape
    (input : Word Bool) (leftScratch : Nat) : Tape Bool :=
  tapeAtCells
    (none :: List.append (input.reverse.map some)
      (List.replicate leftScratch (none : Option Bool)))
    []

theorem FSTScanTargetTape_normalizedOutput
    (input : Word Bool) (leftScratch : Nat) :
    Tape.normalizedOutput (FSTScanTargetTape input leftScratch) =
      input := by
  rw [FSTScanTargetTape, tapeAtCells_normalizedOutput]
  simp [Function.comp_def, List.filterMap_append]

def erasePreservingScanDescription : MachineDescription :=
  eraseTransducer.preservingScanDescription

def erasePreservingScanManualDescription : MachineDescription where
  stateCount := 2
  start := 0
  halt := 1
  transitions :=
    [ { source := 0
        read := none
        write := none
        move := Direction.right
        target := 1 }
    , { source := 0
        read := some false
        write := some false
        move := Direction.right
        target := 0 }
    , { source := 0
        read := some true
        write := some true
        move := Direction.right
        target := 0 } ]

theorem erasePreservingScanDescription_eq_manual :
    erasePreservingScanDescription =
      erasePreservingScanManualDescription := by
  native_decide

theorem erasePreservingScanDescription_wellFormed :
    erasePreservingScanDescription.WellFormed := by
  refine ⟨by decide, by decide, by decide, ?_, ?_⟩
  · exact transition_wellFormed_of_all
      (l := erasePreservingScanDescription.transitions)
      (stateCount := erasePreservingScanDescription.stateCount)
      (by native_decide)
  · exact transition_deterministic_of_all
      (l := erasePreservingScanDescription.transitions)
      (by native_decide)

theorem erasePreservingScanDescription_haltTransitionFree :
    erasePreservingScanDescription.HaltTransitionFree :=
  transition_notFrom_of_all
    (l := erasePreservingScanDescription.transitions)
    (state := erasePreservingScanDescription.halt)
    (by native_decide)

theorem erasePreservingScanDescription_subroutineReady :
    erasePreservingScanDescription.SubroutineReady :=
  ⟨erasePreservingScanDescription_wellFormed,
    erasePreservingScanDescription_haltTransitionFree⟩

theorem erasePreservingScanDescription_step_bit
    (bit : Bool) (left right : List (Option Bool)) :
    erasePreservingScanDescription.runConfig 1
        { state := erasePreservingScanDescription.start
          tape := tapeAtCells left (some bit :: right) } =
      { state := erasePreservingScanDescription.start
        tape := tapeAtCells (some bit :: left) right } := by
  cases bit <;> cases right <;>
    simp [erasePreservingScanDescription_eq_manual,
      erasePreservingScanManualDescription,
      tapeAtCells, runConfig, stepConfig,
      lookupTransition, Matches, Tape.read, Tape.write,
      Tape.move, Tape.moveRight]

theorem erasePreservingScanDescription_step_blank
    (left right : List (Option Bool)) :
    erasePreservingScanDescription.runConfig 1
        { state := erasePreservingScanDescription.start
          tape := tapeAtCells left (none :: right) } =
      { state := erasePreservingScanDescription.halt
        tape := tapeAtCells (none :: left) right } := by
  cases right <;>
    simp [erasePreservingScanDescription_eq_manual,
      erasePreservingScanManualDescription,
      tapeAtCells, runConfig, stepConfig,
      lookupTransition, Matches, Tape.read, Tape.write,
      Tape.move, Tape.moveRight]

theorem erasePreservingScanDescription_run_scan
    (input : Word Bool) (left right : List (Option Bool)) :
    erasePreservingScanDescription.runConfig input.length
        { state := erasePreservingScanDescription.start
          tape :=
            tapeAtCells left
              (List.append (input.map some) (none :: right)) } =
      { state := erasePreservingScanDescription.start
        tape :=
          tapeAtCells
            (List.append (input.reverse.map some) left)
            (none :: right) } := by
  induction input generalizing left with
  | nil =>
      simp [runConfig]
  | cons bit rest ih =>
      rw [show (bit :: rest).length = 1 + rest.length by
        simp
        omega]
      rw [runConfig_add]
      change
        erasePreservingScanDescription.runConfig rest.length
            (erasePreservingScanDescription.runConfig 1
              { state := erasePreservingScanDescription.start
                tape :=
                  tapeAtCells left
                    (some bit ::
                      List.append (rest.map some) (none :: right)) }) =
          { state := erasePreservingScanDescription.start
            tape :=
              tapeAtCells
                (List.append ((bit :: rest).reverse.map some) left)
                (none :: right) }
      rw [erasePreservingScanDescription_step_bit]
      simpa [List.reverse_cons, List.map_append, List.append_assoc] using
        ih (some bit :: left)

theorem erasePreservingScanDescription_run_to_blank
    (input : Word Bool) (left right : List (Option Bool)) :
    erasePreservingScanDescription.runConfig (input.length + 1)
        { state := erasePreservingScanDescription.start
          tape :=
            tapeAtCells left
              (List.append (input.map some) (none :: right)) } =
      { state := erasePreservingScanDescription.halt
        tape :=
          tapeAtCells
            (none :: List.append (input.reverse.map some) left)
            right } := by
  rw [show input.length + 1 = input.length + 1 by rfl]
  rw [runConfig_add]
  rw [erasePreservingScanDescription_run_scan]
  rw [erasePreservingScanDescription_step_blank]

theorem erasePreservingScanDescription_haltsFrom_FSTSourceTape
    (input : Word Bool) (leftScratch : Nat) :
    erasePreservingScanDescription.HaltsFromTape
      (FSTSourceTape input leftScratch)
      (FSTScanTargetTape input leftScratch) := by
  refine ⟨input.length + 1, ?_⟩
  have hrun :=
    erasePreservingScanDescription_run_to_blank input
      (List.replicate leftScratch (none : Option Bool)) []
  constructor
  · simpa [FSTSourceTape, FSTScanTargetTape, List.append_assoc] using
      congrArg MachineDescription.Configuration.state hrun
  · simpa [FSTSourceTape, FSTScanTargetTape, List.append_assoc] using
      congrArg MachineDescription.Configuration.tape hrun

/--
Exact contract for the narrowed source scanner: it preserves the input cells,
moves one step past the trailing blank, and leaves the original left scratch to
the far left of the resulting tape.
-/
def PreservingScanCompiledByDescription
    (D : MachineDescription) : Prop :=
  D.SubroutineReady ∧
    forall input : Word Bool,
    forall leftScratch : Nat,
      D.HaltsFromTape
        (FSTSourceTape input leftScratch)
        (FSTScanTargetTape input leftScratch)

theorem erasePreservingScanDescription_compiled :
    PreservingScanCompiledByDescription
      erasePreservingScanDescription := by
  constructor
  · exact erasePreservingScanDescription_subroutineReady
  · intro input leftScratch
    exact erasePreservingScanDescription_haltsFrom_FSTSourceTape
      input leftScratch

/--
Exact target shape for an erase-then-emit transducer: the emitted output is
immediately to the left of the final head, and the consumed source plus original
left scratch are blank context farther left.
-/
def FSTErasedSourceTargetTape
    (input output : Word Bool) (leftScratch : Nat) : Tape Bool :=
  tapeAtCells
    (List.append (output.reverse.map some)
      (List.append
        (input.reverse.map (fun _ => (none : Option Bool)))
        (List.replicate leftScratch (none : Option Bool))))
    []

theorem FSTErasedSourceTargetTape_normalizedOutput
    (input output : Word Bool) (leftScratch : Nat) :
    Tape.normalizedOutput
        (FSTErasedSourceTargetTape input output leftScratch) =
      output := by
  rw [FSTErasedSourceTargetTape, tapeAtCells_normalizedOutput]
  have hnone :
      List.filterMap (fun _ : Bool => (none : Option Bool)) input = [] := by
    induction input with
    | nil =>
        rfl
    | cons _ rest ih =>
        simp [ih]
  simp [Function.comp_def, List.filterMap_append, hnone]

def FSTConstantBitTargetTape
    (out : Bool) (input : Word Bool) (leftScratch : Nat) : Tape Bool :=
  FSTErasedSourceTargetTape input [out] leftScratch

theorem FSTConstantBitTargetTape_normalizedOutput
    (out : Bool) (input : Word Bool) (leftScratch : Nat) :
    Tape.normalizedOutput
        (FSTConstantBitTargetTape out input leftScratch) = [out] := by
  exact FSTErasedSourceTargetTape_normalizedOutput input [out] leftScratch

theorem boolOutputDescription_step_bit_tapeAtCells
    (out bit : Bool) (left right : List (Option Bool)) :
    (BoolOutputDescription out).runConfig 1
        { state := (BoolOutputDescription out).start
          tape := tapeAtCells left (some bit :: right) } =
      { state := (BoolOutputDescription out).start
        tape := tapeAtCells (none :: left) right } := by
  cases bit <;> cases right <;>
    simp [BoolOutputDescription, tapeAtCells, runConfig, stepConfig,
      lookupTransition, Matches, transition, Tape.read, Tape.write,
      Tape.move, Tape.moveRight]

theorem boolOutputDescription_step_blank_tapeAtCells
    (out : Bool) (left right : List (Option Bool)) :
    (BoolOutputDescription out).runConfig 1
        { state := (BoolOutputDescription out).start
          tape := tapeAtCells left (none :: right) } =
      { state := (BoolOutputDescription out).halt
        tape := tapeAtCells (some out :: left) right } := by
  cases right <;>
    simp [BoolOutputDescription, tapeAtCells, runConfig, stepConfig,
      lookupTransition, Matches, transition, Tape.read, Tape.write,
      Tape.move, Tape.moveRight]

theorem boolOutputDescription_run_scan_tapeAtCells
    (out : Bool) (input : Word Bool)
    (left right : List (Option Bool)) :
    (BoolOutputDescription out).runConfig input.length
        { state := (BoolOutputDescription out).start
          tape :=
            tapeAtCells left
              (List.append (input.map some) (none :: right)) } =
      { state := (BoolOutputDescription out).start
        tape :=
          tapeAtCells
            (List.append
              (input.reverse.map (fun _ => (none : Option Bool))) left)
            (none :: right) } := by
  induction input generalizing left with
  | nil =>
      simp [runConfig]
  | cons bit rest ih =>
      rw [show (bit :: rest).length = 1 + rest.length by
        simp
        omega]
      rw [runConfig_add]
      change
        (BoolOutputDescription out).runConfig rest.length
            ((BoolOutputDescription out).runConfig 1
              { state := (BoolOutputDescription out).start
                tape :=
                  tapeAtCells left
                    (some bit ::
                      List.append (rest.map some) (none :: right)) }) =
          { state := (BoolOutputDescription out).start
            tape :=
              tapeAtCells
                (List.append
                  ((bit :: rest).reverse.map
                    (fun _ => (none : Option Bool))) left)
                (none :: right) }
      rw [boolOutputDescription_step_bit_tapeAtCells]
      simpa [List.reverse_cons, List.map_append, List.append_assoc] using
        ih (none :: left)

theorem boolOutputDescription_run_to_blank_tapeAtCells
    (out : Bool) (input : Word Bool)
    (left right : List (Option Bool)) :
    (BoolOutputDescription out).runConfig (input.length + 1)
        { state := (BoolOutputDescription out).start
          tape :=
            tapeAtCells left
              (List.append (input.map some) (none :: right)) } =
      { state := (BoolOutputDescription out).halt
        tape :=
          tapeAtCells
            (some out ::
              List.append
                (input.reverse.map (fun _ => (none : Option Bool))) left)
            right } := by
  rw [show input.length + 1 = input.length + 1 by rfl]
  rw [runConfig_add]
  rw [boolOutputDescription_run_scan_tapeAtCells]
  rw [boolOutputDescription_step_blank_tapeAtCells]

theorem boolOutputDescription_subroutineReady
    (out : Bool) :
    (BoolOutputDescription out).SubroutineReady :=
  ⟨boolOutputDescription_wellFormed out,
    boolOutputDescription_haltTransitionFree out⟩

theorem boolOutputDescription_haltsFrom_FSTSourceTape
    (out : Bool) (input : Word Bool) (leftScratch : Nat) :
    (BoolOutputDescription out).HaltsFromTape
      (FSTSourceTape input leftScratch)
      (FSTConstantBitTargetTape out input leftScratch) := by
  refine ⟨input.length + 1, ?_⟩
  have hrun :=
    boolOutputDescription_run_to_blank_tapeAtCells out input
      (List.replicate leftScratch (none : Option Bool)) []
  constructor
  · simpa [FSTSourceTape, FSTConstantBitTargetTape,
      FSTErasedSourceTargetTape, List.append_assoc] using
      congrArg MachineDescription.Configuration.state hrun
  · simpa [FSTSourceTape, FSTConstantBitTargetTape,
      FSTErasedSourceTargetTape, List.append_assoc] using
      congrArg MachineDescription.Configuration.tape hrun

/--
The first generated erasing-emitter description.  It is produced from the FST
transition rows rather than named directly as {name}`BoolOutputDescription`.
-/
def generatedConstantBitDescription (out : Bool) : MachineDescription :=
  (constantBitTransducer out).eraseThenEmitBitDescription

theorem generatedConstantBitDescription_eq_boolOutput
    (out : Bool) :
    generatedConstantBitDescription out = BoolOutputDescription out := by
  cases out <;> native_decide

theorem generatedConstantBitDescription_wellFormed
    (out : Bool) :
    (generatedConstantBitDescription out).WellFormed := by
  rw [generatedConstantBitDescription_eq_boolOutput]
  exact boolOutputDescription_wellFormed out

theorem generatedConstantBitDescription_haltTransitionFree
    (out : Bool) :
    (generatedConstantBitDescription out).HaltTransitionFree := by
  rw [generatedConstantBitDescription_eq_boolOutput]
  exact boolOutputDescription_haltTransitionFree out

theorem generatedConstantBitDescription_subroutineReady
    (out : Bool) :
    (generatedConstantBitDescription out).SubroutineReady :=
  ⟨generatedConstantBitDescription_wellFormed out,
    generatedConstantBitDescription_haltTransitionFree out⟩

theorem generatedConstantBitDescription_haltsFrom_FSTSourceTape
    (out : Bool) (input : Word Bool) (leftScratch : Nat) :
    (generatedConstantBitDescription out).HaltsFromTape
      (FSTSourceTape input leftScratch)
      (FSTConstantBitTargetTape out input leftScratch) := by
  rw [generatedConstantBitDescription_eq_boolOutput]
  exact boolOutputDescription_haltsFrom_FSTSourceTape
    out input leftScratch

/--
Target-parameterized exact realization contract for finite transducers.  This
is the general shape used while the framework grows multiple concrete physical
tape layouts.
-/
def ExactCompiledByDescription
    (F : FiniteTransducer) (D : MachineDescription)
    (targetTape : Word Bool -> Word Bool -> Nat -> Tape Bool) : Prop :=
  D.SubroutineReady ∧
    forall input output : Word Bool,
    forall leftScratch : Nat,
      F.RunsToOutput input output ->
        D.HaltsFromTape
          (FSTSourceTape input leftScratch)
          (targetTape input output leftScratch)

theorem constantBitTransducer_compiledByBoolOutputDescription
    (out : Bool) :
    ExactCompiledByDescription
      (constantBitTransducer out)
      (BoolOutputDescription out)
      FSTErasedSourceTargetTape := by
  constructor
  · exact boolOutputDescription_subroutineReady out
  · intro input output leftScratch hrun
    have hout := constantBitTransducer_run out input
    change
      (constantBitTransducer out).runFromStart
          (input.length + 1) input =
        some ((constantBitTransducer out).halt, output) at hrun
    rw [hout] at hrun
    cases hrun
    exact boolOutputDescription_haltsFrom_FSTSourceTape
      out input leftScratch

theorem constantBitTransducer_compiledByGeneratedDescription
    (out : Bool) :
    ExactCompiledByDescription
      (constantBitTransducer out)
      (generatedConstantBitDescription out)
      FSTErasedSourceTargetTape := by
  constructor
  · exact generatedConstantBitDescription_subroutineReady out
  · intro input output leftScratch hrun
    have hout := constantBitTransducer_run out input
    change
      (constantBitTransducer out).runFromStart
          (input.length + 1) input =
        some ((constantBitTransducer out).halt, output) at hrun
    rw [hout] at hrun
    cases hrun
    exact generatedConstantBitDescription_haltsFrom_FSTSourceTape
      out input leftScratch

theorem appendFixedFourBitsRightDescription_step_bit_tapeAtCells
    (b0 b1 b2 b3 bit : Bool) (left right : List (Option Bool)) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig 1
        { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
          tape := tapeAtCells left (some bit :: right) } =
      { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
        tape := tapeAtCells (some bit :: left) right } := by
  cases bit <;> cases right <;>
    simp [AppendFixedFourBitsRightDescription, tapeAtCells,
      runConfig, stepConfig, lookupTransition, Matches, transition,
      Tape.read, Tape.write, Tape.move, Tape.moveRight]

theorem appendFixedFourBitsRightDescription_step_blank_tapeAtCells
    (b0 b1 b2 b3 : Bool) (left : List (Option Bool)) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig 1
        { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
          tape := tapeAtCells left [none] } =
      { state := 1
        tape := tapeAtCells (some b0 :: left) [] } := by
  simp [AppendFixedFourBitsRightDescription, tapeAtCells,
    runConfig, stepConfig, lookupTransition, Matches, transition,
    Tape.read, Tape.write, Tape.move, Tape.moveRight]

theorem appendFixedFourBitsRightDescription_step_write_one_tapeAtCells
    (b0 b1 b2 b3 : Bool) (left : List (Option Bool)) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig 1
        { state := 1
          tape := tapeAtCells left [] } =
      { state := 2
        tape := tapeAtCells (some b1 :: left) [] } := by
  simp [AppendFixedFourBitsRightDescription, tapeAtCells,
    runConfig, stepConfig, lookupTransition, Matches, transition,
    Tape.read, Tape.write, Tape.move, Tape.moveRight]

theorem appendFixedFourBitsRightDescription_step_write_two_tapeAtCells
    (b0 b1 b2 b3 : Bool) (left : List (Option Bool)) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig 1
        { state := 2
          tape := tapeAtCells left [] } =
      { state := 3
        tape := tapeAtCells (some b2 :: left) [] } := by
  simp [AppendFixedFourBitsRightDescription, tapeAtCells,
    runConfig, stepConfig, lookupTransition, Matches, transition,
    Tape.read, Tape.write, Tape.move, Tape.moveRight]

theorem appendFixedFourBitsRightDescription_step_write_three_tapeAtCells
    (b0 b1 b2 b3 : Bool) (left : List (Option Bool)) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig 1
        { state := 3
          tape := tapeAtCells left [] } =
      { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).halt
        tape := tapeAtCells (some b3 :: left) [] } := by
  simp [AppendFixedFourBitsRightDescription, tapeAtCells,
    runConfig, stepConfig, lookupTransition, Matches, transition,
    Tape.read, Tape.write, Tape.move, Tape.moveRight]

theorem appendFixedFourBitsRightDescription_run_scan_tapeAtCells
    (b0 b1 b2 b3 : Bool) (input : Word Bool)
    (left : List (Option Bool)) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig input.length
        { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
          tape := tapeAtCells left (List.append (input.map some) [none]) } =
      { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
        tape :=
          tapeAtCells
            (List.append (input.reverse.map some) left)
            [none] } := by
  induction input generalizing left with
  | nil =>
      simp [runConfig]
  | cons bit rest ih =>
      rw [show (bit :: rest).length = 1 + rest.length by
        simp
        omega]
      rw [runConfig_add]
      change
        (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig
            rest.length
            ((AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig 1
              { state :=
                  (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
                tape :=
                  tapeAtCells left
                    (some bit :: List.append (rest.map some) [none]) }) =
          { state :=
              (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
            tape :=
              tapeAtCells
                (List.append ((bit :: rest).reverse.map some) left)
                [none] }
      rw [appendFixedFourBitsRightDescription_step_bit_tapeAtCells]
      simpa [List.reverse_cons, List.map_append, List.append_assoc] using
        ih (some bit :: left)

theorem appendFixedFourBitsRightDescription_run_write_tapeAtCells
    (b0 b1 b2 b3 : Bool) (left : List (Option Bool)) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig 4
        { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
          tape := tapeAtCells left [none] } =
      { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).halt
        tape :=
          tapeAtCells
            (List.append ([b0, b1, b2, b3].reverse.map some) left)
            [] } := by
  simp [AppendFixedFourBitsRightDescription, tapeAtCells, runConfig,
    stepConfig, lookupTransition, Matches, transition, Tape.read,
    Tape.write, Tape.move, Tape.moveRight]

theorem appendFixedFourBitsRightDescription_run_to_target_tapeAtCells
    (b0 b1 b2 b3 : Bool) (input : Word Bool)
    (left : List (Option Bool)) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).runConfig
        (input.length + 4)
        { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).start
          tape := tapeAtCells left (List.append (input.map some) [none]) } =
      { state := (AppendFixedFourBitsRightDescription b0 b1 b2 b3).halt
        tape :=
          tapeAtCells
            (List.append ([b0, b1, b2, b3].reverse.map some)
              (List.append (input.reverse.map some) left))
            [] } := by
  rw [runConfig_add]
  rw [appendFixedFourBitsRightDescription_run_scan_tapeAtCells]
  rw [appendFixedFourBitsRightDescription_run_write_tapeAtCells]

theorem appendFixedFourBitsRightDescription_subroutineReady
    (b0 b1 b2 b3 : Bool) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).SubroutineReady :=
  ⟨appendFixedFourBitsRightDescription_wellFormed b0 b1 b2 b3,
    appendFixedFourBitsRightDescription_haltTransitionFree b0 b1 b2 b3⟩

theorem appendFixedFourBitsRightDescription_haltsFrom_FSTSourceTape
    (b0 b1 b2 b3 : Bool) (input : Word Bool) (leftScratch : Nat) :
    (AppendFixedFourBitsRightDescription b0 b1 b2 b3).HaltsFromTape
      (FSTSourceTape input leftScratch)
      (FSTRightAppendedTargetTape
        (List.append input [b0, b1, b2, b3]) leftScratch) := by
  refine ⟨input.length + 4, ?_⟩
  have hrun :=
    appendFixedFourBitsRightDescription_run_to_target_tapeAtCells
      b0 b1 b2 b3 input
      (List.replicate leftScratch (none : Option Bool))
  constructor
  · simpa [FSTSourceTape, FSTRightAppendedTargetTape,
      List.reverse_append, List.map_append, List.append_assoc] using
      congrArg MachineDescription.Configuration.state hrun
  · simpa [FSTSourceTape, FSTRightAppendedTargetTape,
      List.reverse_append, List.map_append, List.append_assoc] using
      congrArg MachineDescription.Configuration.tape hrun


end FiniteTransducers
end CommonGround

end Computability
end FoC
