import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.Layout
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.Primitives
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.Composition
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.CursorBasic
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.CursorBoundaryGap
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.CursorBoundaryGapCreator
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.StructuredRefresh
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.SelectedSeparatorRefresh
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.SelectedSeparatorRefreshRuns
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.SingletonRefresh
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.SingletonRefreshRuns
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.ConcreteRefresh
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.CursorComposition
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.CursorSeek
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.CursorHead
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.CursorPipelines
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.PrimitivePipelines
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.ActionSlack
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.Rows
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.RefreshedRows
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.ThreeTapeHelpers
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.ThreeTapeTactic
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.TailedThreeTapeDebug
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.RawTailInsertion
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.Runs
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.RunsStructuredSingleton3
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.Dispatcher
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.DispatcherAssembly
import FoC.Computability.Compiler.Core.CommonGround.FiniteTransducers.StructuredTapeLowering.Projection

set_option doc.verso true

/-!
# Structured multi-tape lowering

Compatibility wrapper for the structured multi-tape lowering modules.

The implementation is split into physical layout facts, primitive lowering
contracts, primitive composition, cursor routines, cursor composition, concrete
cursor pipelines, primitive pipelines, chainable action slack, row machines,
refreshed row machines, run-level trace composition, dispatcher scaffolding,
head-cell routines, and static dispatcher reader-assembly infrastructure. This
module preserves the original import path for downstream files.
-/
