import FoC.Book.Chapter03.Section01
import FoC.Languages.Regular

set_option doc.verso true

namespace FoC
namespace Book
namespace Chapter03
namespace Section02

/-!
# Chapter 3, Section 3.2: Regular Expressions

Regular expressions are syntax trees whose semantics are languages. This page
points to the canonical denotation and regular-language declarations, then keeps
the section focused on concrete book examples. The reusable implementation lives
in {module}`FoC.Languages.RegularExpression` and {module}`FoC.Languages.Regular`.

The page separates syntax from meaning. A regular expression is a finite
object built from constructors such as symbol, alternative, sequence, and star.
Its denotation is the language containing exactly the words matched by that
expression.
-/

open Languages

/-!
## Expression Denotation

Definition 3.2 is formalized by {lit}`RegExp.Denote`. Its constructor equations
are the reusable theorems {lit}`RegExp.denote_empty`,
{lit}`RegExp.denote_eps`, {lit}`RegExp.denote_sym`,
{lit}`RegExp.denote_alt`, {lit}`RegExp.denote_seq`, and
{lit}`RegExp.denote_star`.
-/

/-!
## Regular Languages

A language is regular when it is generated by a regular expression. The
canonical predicate is {lit}`RegularLanguage.Regular`; its expression-based
closure constructors are {lit}`RegularLanguage.union_regular`,
{lit}`RegularLanguage.concat_regular`, {lit}`RegularLanguage.star_regular`, and
{lit}`RegularLanguage.finite_list_regular`.

These closure constructors are the formal version of building larger regular
expressions from smaller ones. If two languages already have regular
expressions, their union, concatenation, and star also have regular
expressions.
-/

/-!
## Example 3.7

The expression {lit}`aStarBStar` denotes any number of a symbols followed by
any number of b symbols. The sample theorem proves one
concrete membership fact by splitting the word into the two star-generated
pieces.

The proof of the sample word supplies the split explicitly: {lit}`aab` is the
concatenation of {lit}`aa`, generated by {lit}`a*`, and {lit}`b`, generated by {lit}`b*`.
-/

def aStarBStar : RegExp Section01.AB :=
  RegExp.seq (RegExp.star (RegExp.sym Section01.AB.a))
    (RegExp.star (RegExp.sym Section01.AB.b))

theorem aStarBStar_accepts_aab :
    [Section01.AB.a, Section01.AB.a, Section01.AB.b] ∈ RegExp.Denote aStarBStar := by
  exists [Section01.AB.a, Section01.AB.a]
  exists [Section01.AB.b]
  constructor
  · exists [[Section01.AB.a], [Section01.AB.a]]
    constructor
    · intro p hp
      cases hp with
      | head =>
          rfl
      | tail _ htail =>
          cases htail with
          | head =>
              rfl
          | tail _ hnil =>
              cases hnil
    · rfl
  constructor
  · exists [[Section01.AB.b]]
    constructor
    · intro p hp
      cases hp with
      | head =>
          rfl
      | tail _ hnil =>
          cases hnil
    · rfl
  · rfl

/-!
## Another Book Expression

The expression `(a|aa|aaa)(bb)*` has a finite initial choice followed by any
number of two-{lit}`b` blocks. The formal expression below uses
{lit}`RegExp.AltList` and {lit}`RegExp.OfWord` to keep the finite alternatives
visible.
-/

def oneToThreeAsThenEvenBs : RegExp Section01.AB :=
  RegExp.seq
    (RegExp.AltList
      [RegExp.OfWord [Section01.AB.a],
       RegExp.OfWord [Section01.AB.a, Section01.AB.a],
       RegExp.OfWord [Section01.AB.a, Section01.AB.a, Section01.AB.a]])
    (RegExp.star (RegExp.OfWord [Section01.AB.b, Section01.AB.b]))

theorem oneToThreeAsThenEvenBs_accepts_aaabbbb :
    [Section01.AB.a, Section01.AB.a, Section01.AB.a,
      Section01.AB.b, Section01.AB.b, Section01.AB.b, Section01.AB.b] ∈
        RegExp.Denote oneToThreeAsThenEvenBs := by
  exists [Section01.AB.a, Section01.AB.a, Section01.AB.a]
  exists [Section01.AB.b, Section01.AB.b, Section01.AB.b, Section01.AB.b]
  constructor
  · apply (RegExp.altList_denote _ _).mpr
    exists RegExp.OfWord [Section01.AB.a, Section01.AB.a, Section01.AB.a]
    constructor
    · simp
    · exact (RegExp.denote_ofWord _ _).mpr rfl
  constructor
  · exists [[Section01.AB.b, Section01.AB.b],
      [Section01.AB.b, Section01.AB.b]]
    constructor
    · intro p hp
      cases hp with
      | head =>
          exact (RegExp.denote_ofWord _ _).mpr rfl
      | tail _ htail =>
          cases htail with
          | head =>
              exact (RegExp.denote_ofWord _ _).mpr rfl
          | tail _ hnil =>
              cases hnil
    · rfl
  · rfl

theorem oneToThreeAsThenEvenBs_accepts_a :
    [Section01.AB.a] ∈ RegExp.Denote oneToThreeAsThenEvenBs := by
  exists [Section01.AB.a]
  exists []
  constructor
  · apply (RegExp.altList_denote _ _).mpr
    exists RegExp.OfWord [Section01.AB.a]
    constructor
    · simp
    · exact (RegExp.denote_ofWord _ _).mpr rfl
  constructor
  · exact Language.star_empty_word _
  · rfl

end Section02
end Chapter03
end Book
end FoC
