import FoC.Book.Chapter03.Section01
import FoC.Languages.Regular

set_option doc.verso true

namespace FoC
namespace Book
namespace Chapter03
namespace Section02

/-!
# Chapter 3, Section 3.2: Regular Expressions

Regular expressions are syntax trees whose semantics are languages. This page
points to the canonical denotation and regular-language declarations, then keeps
the section focused on concrete book examples. The reusable implementation lives
in {module}`FoC.Languages.RegularExpression` and {module}`FoC.Languages.Regular`.
-/

open Languages

/-!
## Expression Denotation

Definition 3.2 is formalized by {lit}`RegExp.Denote`. Its constructor equations
are the reusable theorems {lit}`RegExp.denote_empty`,
{lit}`RegExp.denote_eps`, {lit}`RegExp.denote_sym`,
{lit}`RegExp.denote_alt`, {lit}`RegExp.denote_seq`, and
{lit}`RegExp.denote_star`.
-/

/-!
## Regular Languages

A language is regular when it is generated by a regular expression. The
canonical predicate is {lit}`RegularLanguage.Regular`; its expression-based
closure constructors are {lit}`RegularLanguage.union_regular`,
{lit}`RegularLanguage.concat_regular`, {lit}`RegularLanguage.star_regular`, and
{lit}`RegularLanguage.finite_list_regular`.
-/

/-!
## Example 3.7

The expression {lit}`aStarBStar` denotes any number of a symbols followed by
any number of b symbols. The sample theorem proves one
concrete membership fact by splitting the word into the two star-generated
pieces.
-/

def aStarBStar : RegExp Section01.AB :=
  RegExp.seq (RegExp.star (RegExp.sym Section01.AB.a))
    (RegExp.star (RegExp.sym Section01.AB.b))

theorem aStarBStar_accepts_aab :
    [Section01.AB.a, Section01.AB.a, Section01.AB.b] ∈ RegExp.Denote aStarBStar := by
  exists [Section01.AB.a, Section01.AB.a]
  exists [Section01.AB.b]
  constructor
  · exists [[Section01.AB.a], [Section01.AB.a]]
    constructor
    · intro p hp
      cases hp with
      | head =>
          rfl
      | tail _ htail =>
          cases htail with
          | head =>
              rfl
          | tail _ hnil =>
              cases hnil
    · rfl
  constructor
  · exists [[Section01.AB.b]]
    constructor
    · intro p hp
      cases hp with
      | head =>
          rfl
      | tail _ hnil =>
          cases hnil
    · rfl
  · rfl

end Section02
end Chapter03
end Book
end FoC
