import FoC.Book.Chapter03.Section01
import FoC.Languages.Regular

set_option doc.verso true

namespace FoC
namespace Book
namespace Chapter03
namespace Section02

/-!
# Chapter 3, Section 3.2: Regular Expressions

Regular expressions are syntax trees whose semantics are languages. This page
states the denotation of each constructor and then records the closure facts
that identify regular languages as those generated by some regular expression.
The reusable implementation lives in {module}`FoC.Languages.RegularExpression`
and {module}`FoC.Languages.Regular`.
-/

open Languages

/-!
## Expression Denotation

The first group unfolds the language denoted by the empty expression, epsilon,
symbols, alternation, concatenation, and star. These are the formal versions
of Definitions 3.2 and 3.3.
-/

theorem regular_expression_empty_language (w : Word alpha) :
    w ∈ RegExp.Denote (RegExp.empty : RegExp alpha) <-> False :=
  RegExp.denote_empty w

theorem empty_string_expression_language (w : Word alpha) :
    w ∈ RegExp.Denote (RegExp.eps : RegExp alpha) <-> w = Word.Empty :=
  RegExp.denote_eps w

theorem symbol_expression_language (a : alpha) (w : Word alpha) :
    w ∈ RegExp.Denote (RegExp.sym a) <-> w = Word.Symbol a :=
  RegExp.denote_sym a w

theorem alternation_expression_language (r s : RegExp alpha) (w : Word alpha) :
    w ∈ RegExp.Denote (RegExp.alt r s) <->
      w ∈ RegExp.Denote r ∨ w ∈ RegExp.Denote s :=
  RegExp.denote_alt r s w

theorem concatenation_expression_language (r s : RegExp alpha) (w : Word alpha) :
    w ∈ RegExp.Denote (RegExp.seq r s) <->
      exists x y, x ∈ RegExp.Denote r ∧ y ∈ RegExp.Denote s ∧ w = Word.Concat x y :=
  RegExp.denote_seq r s w

theorem star_expression_language (r : RegExp alpha) (w : Word alpha) :
    w ∈ RegExp.Denote (RegExp.star r) <->
      w ∈ Language.Star (RegExp.Denote r) :=
  RegExp.denote_star r w

/-!
## Regular Languages

A language is regular when it is generated by a regular expression. The
closure theorems show how the corresponding expression constructors preserve
regularity.
-/

theorem regular_language_definition (L : Language alpha) :
    RegularLanguage.Regular L <-> exists r : RegExp alpha, RegExp.Generates r L :=
  Iff.rfl

theorem union_of_regular_languages {L M : Language alpha}
    (hL : RegularLanguage.Regular L) (hM : RegularLanguage.Regular M) :
    RegularLanguage.Regular (Language.Union L M) :=
  RegularLanguage.union_regular hL hM

theorem concatenation_of_regular_languages {L M : Language alpha}
    (hL : RegularLanguage.Regular L) (hM : RegularLanguage.Regular M) :
    RegularLanguage.Regular (Language.Concat L M) :=
  RegularLanguage.concat_regular hL hM

theorem kleene_star_of_regular_language {L : Language alpha}
    (hL : RegularLanguage.Regular L) :
    RegularLanguage.Regular (Language.Star L) :=
  RegularLanguage.star_regular hL

theorem finite_languages_are_regular (ws : List (Word alpha)) :
    RegularLanguage.Regular (fun w => w ∈ ws) :=
  RegularLanguage.finite_list_regular ws

/-!
## Example 3.7

The expression {lit}`aStarBStar` denotes any number of a symbols followed by
any number of b symbols. The sample theorem proves one
concrete membership fact by splitting the word into the two star-generated
pieces.
-/

def aStarBStar : RegExp Section01.AB :=
  RegExp.seq (RegExp.star (RegExp.sym Section01.AB.a))
    (RegExp.star (RegExp.sym Section01.AB.b))

theorem aStarBStar_accepts_aab :
    [Section01.AB.a, Section01.AB.a, Section01.AB.b] ∈ RegExp.Denote aStarBStar := by
  exists [Section01.AB.a, Section01.AB.a]
  exists [Section01.AB.b]
  constructor
  · exists [[Section01.AB.a], [Section01.AB.a]]
    constructor
    · intro p hp
      cases hp with
      | head =>
          rfl
      | tail _ htail =>
          cases htail with
          | head =>
              rfl
          | tail _ hnil =>
              cases hnil
    · rfl
  constructor
  · exists [[Section01.AB.b]]
    constructor
    · intro p hp
      cases hp with
      | head =>
          rfl
      | tail _ hnil =>
          cases hnil
    · rfl
  · rfl

end Section02
end Chapter03
end Book
end FoC
